-- MySQL Script generated by MySQL Workbench
-- Mon Nov 20 09:53:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tabAdministrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabAdministrativo` (
  `admUsuID` INT(5) NOT NULL,
  `admUsu` VARCHAR(10) NOT NULL,
  `admSenha` VARCHAR(8) NULL,
  `admNome` VARCHAR(45) NULL,
  `admTelefone` VARCHAR(45) NULL,
  `admEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`admUsuID`, `admUsu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabEstoquistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabEstoquistas` (
  `estUsuID` INT NOT NULL AUTO_INCREMENT,
  `estUsu` VARCHAR(45) NOT NULL,
  `estSenha` VARCHAR(45) NULL,
  `estNome` VARCHAR(45) NULL,
  `estTelefone` VARCHAR(45) NULL,
  `estCidade` VARCHAR(45) NULL,
  `estBairro` VARCHAR(45) NULL,
  `estEnd` VARCHAR(45) NULL,
  PRIMARY KEY (`estUsuID`),
  UNIQUE INDEX `estUsu_UNIQUE` (`estUsu` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabCliente` (
  `cliUsuID` INT NOT NULL AUTO_INCREMENT,
  `cliUsu` VARCHAR(10) NOT NULL,
  `cliSenha` VARCHAR(45) NOT NULL,
  `cliNome` VARCHAR(45) NOT NULL,
  `cliTelefone` VARCHAR(45) NULL,
  `cliImage` VARCHAR(45) NULL,
  PRIMARY KEY (`cliUsuID`),
  UNIQUE INDEX `cliSenha_UNIQUE` (`cliSenha` ASC) VISIBLE,
  UNIQUE INDEX `cliUsuID_UNIQUE` (`cliUsuID` ASC) VISIBLE,
  UNIQUE INDEX `cliUsu_UNIQUE` (`cliUsu` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabProduto` (
  `prodID` INT NOT NULL AUTO_INCREMENT,
  `prodNome` VARCHAR(45) NOT NULL,
  `prodDescricao` VARCHAR(45) NULL,
  `prodPreco` VARCHAR(45) NOT NULL,
  `prodImagem` VARCHAR(45) NULL,
  `ProdTipo` VARCHAR(45) NOT NULL,
  `prodQtd` VARCHAR(45) NULL,
  PRIMARY KEY (`prodID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabCarrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabCarrinho` (
  `carID` INT NOT NULL AUTO_INCREMENT,
  `FK_cliID_CARRINHO` INT NOT NULL,
  `carQtd` INT NULL,
  `FK_prodID_CARRINHO` INT NOT NULL,
  PRIMARY KEY (`carID`),
  UNIQUE INDEX `cliUsu_UNIQUE` (`FK_cliID_CARRINHO` ASC) VISIBLE,
  INDEX `fk_prodID_PRODUTO_idx` (`FK_prodID_CARRINHO` ASC) VISIBLE,
  UNIQUE INDEX `carID_UNIQUE` (`carID` ASC) VISIBLE,
  UNIQUE INDEX `prodID_FK_UNIQUE` (`FK_prodID_CARRINHO` ASC) VISIBLE,
  CONSTRAINT `fk_cliUsu_CARRINHO`
    FOREIGN KEY (`FK_cliID_CARRINHO`)
    REFERENCES `mydb`.`tabCliente` (`cliUsuID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prodID_PRODUTO`
    FOREIGN KEY (`FK_prodID_CARRINHO`)
    REFERENCES `mydb`.`tabProduto` (`prodID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabOrdemPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabOrdemPedido` (
  `ordemPedID` INT NOT NULL AUTO_INCREMENT,
  `FK_estID_ORDP` INT NOT NULL,
  `FK_carID_ORDP` INT NOT NULL,
  `ordTotal` REAL NULL,
  PRIMARY KEY (`ordemPedID`),
  UNIQUE INDEX `cliUsu_FK_UNIQUE` (`FK_estID_ORDP` ASC) VISIBLE,
  UNIQUE INDEX `carID_FK_UNIQUE` (`FK_carID_ORDP` ASC) VISIBLE,
  CONSTRAINT `carID_FK`
    FOREIGN KEY (`FK_carID_ORDP`)
    REFERENCES `mydb`.`tabCarrinho` (`carID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabEndereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabEndereco` (
  `endID` INT NOT NULL AUTO_INCREMENT,
  `endLogradouro` VARCHAR(45) NULL,
  `endBaiirro` VARCHAR(45) NULL,
  `endCidade` CHAR(2) NULL,
  `endReferencia` VARCHAR(45) NULL,
  `FK_cliID` INT NULL,
  PRIMARY KEY (`endID`),
  UNIQUE INDEX `endID_UNIQUE` (`endID` ASC) VISIBLE,
  INDEX `FK_cliID_CLENDERECO_idx` (`FK_cliID` ASC) VISIBLE,
  CONSTRAINT `FK_cliID_CLENDERECO`
    FOREIGN KEY (`FK_cliID`)
    REFERENCES `mydb`.`tabCliente` (`cliUsuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabMetodoPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabMetodoPagamento` (
  `idMetodoPagamento` INT NOT NULL AUTO_INCREMENT,
  `metodoPagamento` VARCHAR(10) NULL,
  `disponibilidade` TINYINT(1) NULL,
  PRIMARY KEY (`idMetodoPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabCompra` (
  `compraID` INT NOT NULL AUTO_INCREMENT,
  `FK_ordemPedID_COMPRA` INT NOT NULL,
  `FK_cliID_COMPRA` INT NOT NULL,
  `FK_carID_COMPRA` INT NOT NULL,
  `compraTotal` REAL NULL,
  `FK_endID` INT NOT NULL,
  `FK_metPAG` INT NOT NULL,
  PRIMARY KEY (`compraID`),
  UNIQUE INDEX `ordemPed_UNIQUE` (`FK_ordemPedID_COMPRA` ASC) VISIBLE,
  UNIQUE INDEX `FK_cliID_UNIQUE` (`FK_cliID_COMPRA` ASC) VISIBLE,
  UNIQUE INDEX `FK_carID_UNIQUE` (`FK_carID_COMPRA` ASC) VISIBLE,
  UNIQUE INDEX `FK_endID_UNIQUE` (`FK_endID` ASC) VISIBLE,
  UNIQUE INDEX `fk_metPAG_UNIQUE` (`FK_metPAG` ASC) VISIBLE,
  CONSTRAINT `FK_ordemPedID_ORCOMPRA`
    FOREIGN KEY (`FK_ordemPedID_COMPRA`)
    REFERENCES `mydb`.`tabOrdemPedido` (`ordemPedID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_cliID_CLCOMPRA`
    FOREIGN KEY (`FK_cliID_COMPRA`)
    REFERENCES `mydb`.`tabCliente` (`cliUsuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_carID_CACOMPRA`
    FOREIGN KEY (`FK_carID_COMPRA`)
    REFERENCES `mydb`.`tabCarrinho` (`carID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_endID_ENCOMPRA`
    FOREIGN KEY (`FK_endID`)
    REFERENCES `mydb`.`tabEndereco` (`endID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_metPag_MECOMPRA`
    FOREIGN KEY (`FK_metPAG`)
    REFERENCES `mydb`.`tabMetodoPagamento` (`idMetodoPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabPedido` (
  `pedID` INT NOT NULL AUTO_INCREMENT,
  `FK_vendID` INT NOT NULL,
  `ordemPedID` INT NOT NULL,
  `pedTotal` REAL NOT NULL,
  `pedData` DATE NOT NULL,
  PRIMARY KEY (`pedID`),
  UNIQUE INDEX `pedID_UNIQUE` (`pedID` ASC) VISIBLE,
  UNIQUE INDEX `FK_vendID_UNIQUE` (`FK_vendID` ASC) VISIBLE,
  UNIQUE INDEX `ordemPedID_UNIQUE` (`ordemPedID` ASC) VISIBLE,
  UNIQUE INDEX `pedTotal_UNIQUE` (`pedTotal` ASC) VISIBLE,
  UNIQUE INDEX `pedData_UNIQUE` (`pedData` ASC) VISIBLE,
  CONSTRAINT `FK_vendID_VENDAS`
    FOREIGN KEY (`FK_vendID`)
    REFERENCES `mydb`.`tabCompra` (`compraID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabEntrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabEntrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `entregastatus` VARCHAR(45) NULL,
  `entrepedID` INT NULL,
  PRIMARY KEY (`idEntrega`),
  INDEX `FK_entrepedID_PEDIDO_idx` (`entrepedID` ASC) VISIBLE,
  CONSTRAINT `FK_entrepedID_PEDIDO`
    FOREIGN KEY (`entrepedID`)
    REFERENCES `mydb`.`tabPedido` (`pedID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabFornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabFornecedor` (
  `fornecedorID` INT NOT NULL AUTO_INCREMENT,
  `fornecedorNome` VARCHAR(45) NOT NULL,
  `fornecedorTelefone` VARCHAR(45) NOT NULL,
  `fornecedorEmail` VARCHAR(45) NULL,
  `fornecedorEndereco` VARCHAR(45) NULL,
  `fornecedorDescricao` VARCHAR(250) NULL,
  `fornecedorTipo` VARCHAR(45) NULL,
  PRIMARY KEY (`fornecedorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabFornecedorProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabFornecedorProduto` (
  `FPID` INT NOT NULL AUTO_INCREMENT,
  `fpNome` VARCHAR(45) NOT NULL,
  `fpPreco` VARCHAR(45) NOT NULL,
  `fpTipo` VARCHAR(45) NULL,
  `fpQtd` INT NULL,
  PRIMARY KEY (`FPID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabConfigEstoquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabConfigEstoquista` (
  `estID` INT NOT NULL,
  `FPID_FK` INT NULL,
  `prodID_FK` INT NULL,
  `fornecedorID_FK` INT NULL,
  PRIMARY KEY (`estID`),
  INDEX `prodID_FK_idx` (`prodID_FK` ASC) VISIBLE,
  INDEX `FPID_FK_idx` (`FPID_FK` ASC) VISIBLE,
  INDEX `fornecedorID_FK_idx` (`fornecedorID_FK` ASC) VISIBLE,
  CONSTRAINT `estID`
    FOREIGN KEY (`estID`)
    REFERENCES `mydb`.`tabEstoquistas` (`estUsuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prodID_FK`
    FOREIGN KEY (`prodID_FK`)
    REFERENCES `mydb`.`tabProduto` (`prodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FPID_FK`
    FOREIGN KEY (`FPID_FK`)
    REFERENCES `mydb`.`tabFornecedorProduto` (`FPID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fornecedorID_FK`
    FOREIGN KEY (`fornecedorID_FK`)
    REFERENCES `mydb`.`tabFornecedor` (`fornecedorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabLucros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabLucros` (
  `lucrosID` INT NOT NULL AUTO_INCREMENT,
  `lucrosdata` DATE NULL,
  `pedidoID_FK` INT NULL,
  PRIMARY KEY (`lucrosID`),
  CONSTRAINT `pedidoID_FK`
    FOREIGN KEY (`lucrosID`)
    REFERENCES `mydb`.`tabPedido` (`pedID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabGastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabGastos` (
  `idtabGastos` INT NOT NULL,
  `FPID_FK` INT NULL,
  PRIMARY KEY (`idtabGastos`),
  INDEX `fornecedorProduto_FK_idx` (`FPID_FK` ASC) VISIBLE,
  CONSTRAINT `fornecedorProduto_FK`
    FOREIGN KEY (`FPID_FK`)
    REFERENCES `mydb`.`tabFornecedorProduto` (`FPID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabContabilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabContabilidade` (
  `contID` INT NOT NULL,
  `lucrosID_FK` INT NULL,
  `ganhosID_FK` INT NULL,
  `admID_FK` INT NULL,
  PRIMARY KEY (`contID`),
  INDEX `lucrosID_FK_idx` (`lucrosID_FK` ASC) VISIBLE,
  INDEX `gastosID_FK_idx` (`ganhosID_FK` ASC) VISIBLE,
  INDEX `admID_FK_idx` (`admID_FK` ASC) VISIBLE,
  CONSTRAINT `lucrosID_FK`
    FOREIGN KEY (`lucrosID_FK`)
    REFERENCES `mydb`.`tabLucros` (`lucrosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gastosID_FK`
    FOREIGN KEY (`ganhosID_FK`)
    REFERENCES `mydb`.`tabGastos` (`idtabGastos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `admID_FK`
    FOREIGN KEY (`admID_FK`)
    REFERENCES `mydb`.`tabAdministrativo` (`admUsuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabComentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabComentario` (
  `comentarioID` INT NOT NULL,
  `FK_cliID_COMENT` INT NULL,
  `FK_prodID_COMENT` INT NULL,
  `comentario` VARCHAR(1000) NULL,
  PRIMARY KEY (`comentarioID`),
  INDEX `cliID_FK_idx` (`FK_cliID_COMENT` ASC) VISIBLE,
  INDEX `prodID_FK_idx` (`FK_prodID_COMENT` ASC) VISIBLE,
  CONSTRAINT `cliID_FK_COMENT`
    FOREIGN KEY (`FK_cliID_COMENT`)
    REFERENCES `mydb`.`tabCliente` (`cliUsuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prodID_FK_COMENT`
    FOREIGN KEY (`FK_prodID_COMENT`)
    REFERENCES `mydb`.`tabProduto` (`prodID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabcadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabcadastro` (
  `cadastroID` INT NOT NULL,
  `cliID_FK_CAD` INT NULL,
  `estID_FK_CAD` INT NULL,
  `admID_FK_CAD` INT NULL,
  `cadastroData` DATE NULL,
  PRIMARY KEY (`cadastroID`),
  INDEX `cliID_FK_idx` (`cliID_FK_CAD` ASC) VISIBLE,
  INDEX `estID_FK_CAD_idx` (`estID_FK_CAD` ASC) VISIBLE,
  INDEX `admID_FK_CAD_idx` (`admID_FK_CAD` ASC) VISIBLE,
  CONSTRAINT `cliID_FK_CAD`
    FOREIGN KEY (`cliID_FK_CAD`)
    REFERENCES `mydb`.`tabCliente` (`cliUsuID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `estID_FK_CAD`
    FOREIGN KEY (`estID_FK_CAD`)
    REFERENCES `mydb`.`tabEstoquistas` (`estUsuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `admID_FK_CAD`
    FOREIGN KEY (`admID_FK_CAD`)
    REFERENCES `mydb`.`tabAdministrativo` (`admUsuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SHOW databases;
show tables;
SHOW COLUMNS from tabcarrinho;
SHOW COLUMNS from tabCliente;
